### PR TITLE
fix: GcpProjectIdProvider when using Secret Manager

### LINKED ISSUE #3181: SecretManager autoconfiguration ignores and superseeds spring.cloud.gcp.project-id
This issue is regarding the projectId value returned by GcpProjectIdProvider when SecretManager is enabled.

I know, as an example, theses two closed issues, but I think they doesn't cover the root cause:
* https://github.com/GoogleCloudPlatform/spring-cloud-gcp/issues/2698
* https://github.com/GoogleCloudPlatform/spring-cloud-gcp/issues/1793

Regarding [the documentation](https://googlecloudplatform.github.io/spring-cloud-gcp/reference/html/index.html#project-id), the `GcpProjectIdProvider.getProjectId()` method will always return the value of the property `spring.cloud.gcp.project-id` if set. There is no limitation regarding the use of SecretManager.

In addition, in [the SecretManager section of the documentation](https://googlecloudplatform.github.io/spring-cloud-gcp/reference/html/index.html#configuration-11) the project-id is (if not set as property): "By default, infers the project from [Application Default Credentials](https://cloud.google.com/docs/authentication/production)"

I wasn't able to to determine the method who creates the `GcpProjectIdProvider` bean for the [SecretManagerAutoConfiguration](https://github.com/GoogleCloudPlatform/spring-cloud-gcp/blob/main/spring-cloud-gcp-autoconfigure/src/main/java/com/google/cloud/spring/autoconfigure/secretmanager/GcpSecretManagerAutoConfiguration.java#L51), but it definitivley get its values not from the `spring.cloud.gcp.project-id` property.
Because of this presence of a `GcpProjectIdProvider` bean there is no propper one created in [GcpContextAutoConfiguration](https://github.com/GoogleCloudPlatform/spring-cloud-gcp/blob/main/spring-cloud-gcp-autoconfigure/src/main/java/com/google/cloud/spring/autoconfigure/core/GcpContextAutoConfiguration.java#L65-L78).

I created a simple repository to demonstrate the issue: https://github.com/mieseprem/projectIdIssue
Please keep in mind that this issue is not on how to access secrets or other services in GCP. This is only about how the project-id value is determined and provided to all beans that relay on the `GcpProjectIdProvider`

In my example project, there is a profile named "xxx" and the project-id is set to a specific value. If you run the application with active profile "xxx" you will see 2 things:
* the `GcpProjectIdProvider` is created via 'GcpContextAutoConfiguration'
* the project-id value is the one set as `spring.cloud.gcp.project-id`
```log
...
2024-08-30T11:08:56.545+02:00  INFO 99194 --- [demo] [           main] com.example.demo.DemoApplication         : The following 1 profile is active: "xxx"
...
2024-08-30T11:08:56.680+02:00  INFO 99194 --- [demo] [           main] c.g.c.s.a.c.GcpContextAutoConfiguration  : The default project ID is my-project-id
...
2024-08-30T11:08:57.237+02:00  INFO 99194 --- [demo] [           main] com.example.demo.DemoApplication         : Started DemoApplication in 0.813 seconds (process running for 1.003)
Project ID: my-project-id
...
```

If you now enable the Config Data API to get Secret value via "sm://" prefix, the `GcpProjectIdProvider` is created in a different way and `spring.cloud.gcp.project-id` is not used anymore.
(Please uncomment these lines in [application.yml](https://github.com/mieseprem/projectIdIssue/blob/main/src/main/resources/application.yml#L5-L7) and run again with "xxx" profile)

You'll see, the `GcpProjectIdProvider` is **not** created via `GcpContextAutoConfiguration` but - strong guess - [determined from this places](https://cloud.google.com/java/docs/reference/google-cloud-core/latest/com.google.cloud.ServiceOptions#com_google_cloud_ServiceOptions_getDefaultProjectId__):
1. The project ID specified by the GOOGLE_CLOUD_PROJECT environment variable
2. The Google App Engine project ID
3. The project ID specified in the JSON credentials file pointed by the GOOGLE_APPLICATION_CREDENTIALS environment variable
4. The Google Cloud SDK project ID
5. The Google Compute Engine project ID, from the Google Compute Engine Metadata Server

If none of them is present/configured this will happen:
```log
...
2024-08-30T12:07:52.190+02:00  INFO 421 --- [demo] [           main] com.example.demo.DemoApplication         : The following 1 profile is active: "xxx"
...
2024-08-30T12:07:52.382+02:00  INFO 421 --- [demo] [           main] com.example.demo.DemoApplication         : Started DemoApplication in 1.151 seconds (process running for 1.403)
Project ID: null
...
```
Note: even if I move `spring.cloud.gcp.project-id` into default profile it is ignored as of activating `spring.cloud.import`

As a workarount we can provide the project-id via `spring.cloud.gcp.secretmanager.project-id` property.
(Please uncomment these lines in [application.yml](https://github.com/mieseprem/projectIdIssue/blob/main/src/main/resources/application.yml#L9-L14)
As a result you'll see the project-id isn't `null` anymore, but the variable is not resolved:
```log
...
2024-08-30T12:15:08.602+02:00  INFO 589 --- [demo] [           main] com.example.demo.DemoApplication         : The following 1 profile is active: "xxx"
...
2024-08-30T12:15:08.800+02:00  INFO 589 --- [demo] [           main] com.example.demo.DemoApplication         : Started DemoApplication in 1.034 seconds (process running for 1.383)
Project ID: ${spring.cloud.gcp.project-id}
...
```
Btw. the `spring.cloud.gcp.secretmanager.project-id` property can't be set in any profile (only in default). If set in any profile it is ignored.

**Now, why do I think this is a bug (or at least not the expected behaviour)?**

I think it's not okay that the SecretManager auto configuration disturbes all other GCP beans from being configured propperly.
* if `spring.cloud.gcp.project-id` is set it should be used
* setting `spring.cloud.gcp.secretmanager.project-id` shoul'd change the ProjectIdProvider for all GCP components
* if `spring.cloud.gcp.secretmanager.project-id` can't be set in a profile or can't use a property value from a profile there is no way to configure a value based on a profile from within springboot. I must provide the value from outside via paramater, env var, or from the list mentioned further up.

### LINKED ISSUE #3564: GcpSecretManagerAutoConfiguration should have @AutoConfigureAfter(GcpContextAutoConfiguration.class)
When I upgrading to v6.0.0 the order on how `GcpSecretManagerAutoConfiguration` is loaded changed, resulting in an error on some of our integration tests.

I think this class should have `@AutoConfigureAfter(GcpContextAutoConfiguration.class)` since it assumes a bean of type `CredentialsProvider` .

https://github.com/GoogleCloudPlatform/spring-cloud-gcp/blob/84706c7add68ed013be7a8ed537b5b9726ac22be/spring-cloud-gcp-autoconfigure/src/main/java/com/google/cloud/spring/autoconfigure/secretmanager/GcpSecretManagerAutoConfiguration.java#L42

### PR DESCRIPTION
**Pull request by zhumin8**
fixes #3181 , also fixes #3564

cherry-picked changes from https://github.com/GoogleCloudPlatform/spring-cloud-gcp/pull/3383 to allow ci properly run. Adding tests.
@PatrickGotthard 's original comment on root cause: https://github.com/GoogleCloudPlatform/spring-cloud-gcp/issues/3181#issuecomment-2478682585

When using Secret Manager (sm) module, expected behavior for GcpProjectIdProvider should be:
- in Spring Bootstrap Phase (where sm if configured), order of discovery: secretmanager.project-id >>  gcp.project-id >> default (according to DefaultGcpProjectIdProvider)
- in Application Context, GcpProjectIdProvider bean should behave similar to other modules, with no knowledge of secretmanager.project-id, thus: gcp.project-id >> default

Current behavior prior to this fix, the discovery order for both cases are:
- secretmanager.project-id >> default 

Fix is to let SecretManagerConfigDataLocationResolver recognizing GcpProperties and **not** promoting GcpProjectIdProvider to application context.

Thanks @PatrickGotthard for your contribution!

### CODE REVIEW

File: spring-cloud-gcp-autoconfigure/src/main/java/com/google/cloud/spring/autoconfigure/secretmanager/SecretManagerConfigDataLocationResolver.java [hunk 1]
```diff
@@ -80,30 +84,44 @@ private static void registerSecretManagerBeans(ConfigDataLocationResolverContext
         // lazy register the client solely for unit test.
         BootstrapRegistry.InstanceSupplier.from(() -> createSecretManagerClient(context)));
     // Register the GCP Project ID provider.
-    registerAndPromoteBean(
+    registerBean(
```
Comment (zhumin8) [inline spring-cloud-gcp-autoconfigure/src/main/java/com/google/cloud/spring/autoconfigure/secretmanager/SecretManagerConfigDataLocationResolver.java]: re: https://github.com/GoogleCloudPlatform/spring-cloud-gcp/pull/3383#discussion_r1973994631
"Promote" is needed for beans that are needed during the ConfigData loading phase and are also required by the application at runtime. Definition [here](https://github.com/GoogleCloudPlatform/spring-cloud-gcp/blob/26e0deeadf02db31390b40d3e24608499e7274fb/spring-cloud-gcp-autoconfigure/src/main/java/com/google/cloud/spring/autoconfigure/secretmanager/SecretManagerConfigDataLocationResolver.java#L178-L194)
In this case, we do expose this bean so it is needed.
https://github.com/GoogleCloudPlatform/spring-cloud-gcp/blob/26e0deeadf02db31390b40d3e24608499e7274fb/spring-cloud-gcp-autoconfigure/src/main/java/com/google/cloud/spring/autoconfigure/core/GcpContextAutoConfiguration.java#L65-L67

Reverting this change.

File: spring-cloud-gcp-autoconfigure/src/main/java/com/google/cloud/spring/autoconfigure/secretmanager/GcpSecretManagerAutoConfiguration.java [hunk 2]
```diff
@@ -39,6 +41,7 @@
 @EnableConfigurationProperties(GcpSecretManagerProperties.class)
 @ConditionalOnClass(SecretManagerTemplate.class)
 @ConditionalOnProperty(value = "spring.cloud.gcp.secretmanager.enabled", matchIfMissing = true)
+@AutoConfigureAfter(GcpContextAutoConfiguration.class)
```
Comment (zhumin8) [inline spring-cloud-gcp-autoconfigure/src/main/java/com/google/cloud/spring/autoconfigure/secretmanager/GcpSecretManagerAutoConfiguration.java:44]: I believe this was missed. Adding this allows beans defined in [GcpContextAutoConfiguration.java](https://github.com/GoogleCloudPlatform/spring-cloud-gcp/blob/main/spring-cloud-gcp-autoconfigure/src/main/java/com/google/cloud/spring/autoconfigure/core/GcpContextAutoConfiguration.java) be accessible in application.
In this case specifically, together with registerAndPromoteBean() in resolver, let application access the correct GcpProjectIdProvider by injecting it.

File: spring-cloud-gcp-samples/spring-cloud-gcp-secretmanager-sample/src/test/java/com/example/SecretManagerSamplePropertyIdTest.java [hunk 3]
```diff
@@ -0,0 +1,44 @@
...
+  // When secretmanager.project-id and project gcp.project-id are both set,
+  // secretManagerTemplate should recognize secretmanager.project-id
+  // but gcpProjectIdProvider should only capture gcp.project-id
+  @Test
+  void testProjectIdCorrect() {
+    String projectId = secretManagerTemplate.getProjectId();
+    assertThat(projectId).isEqualTo("spring-cloud-gcp-ci");
+    String gcpProjectId = gcpProjectIdProvider.getProjectId();
+    assertThat(gcpProjectId).isEqualTo("gcp-project-id");
+  }
```
Comment (mieseprem) [inline spring-cloud-gcp-samples/spring-cloud-gcp-secretmanager-sample/src/test/java/com/example/SecretManagerSamplePropertyIdTest.java:43]: Do you mind adding `spring.cloud.import=sm@` to the property list?
This property triggered the issue in https://github.com/GoogleCloudPlatform/spring-cloud-gcp/issues/3181 and in a sense of regression-prevention test it would be nice to have it in.

Comment (mieseprem) [reply spring-cloud-gcp-samples/spring-cloud-gcp-secretmanager-sample/src/test/java/com/example/SecretManagerSamplePropertyIdTest.java:43]: I used your branch to run tests in my project and I can verify your changes lead to a valid projectId in global gcpProjectIdProvider.

But, now I know what to add to a new Issue (as said in https://github.com/GoogleCloudPlatform/spring-cloud-gcp/issues/3181#issuecomment-2724211664). 
For now, you can leave out to add `spring.cloud.import=sm@`. This will be addressed in the other Issue.

**Review by meltsufin — APPROVED** [review]

**Review by jinseopkim0 — APPROVED** [review]

File: spring-cloud-gcp-autoconfigure/src/test/java/com/google/cloud/spring/autoconfigure/secretmanager/SecretManagerCompatibilityTests.java [hunk 4]
```diff
@@ -34,17 +33,18 @@ class SecretManagerCompatibilityTests {
...
+        Arguments.of("sm@", "spring.cloud.gcp.secretmanager.project-id="));
   }
 
   @BeforeEach
   void init() {
     application = new SpringApplicationBuilder(SecretManagerCompatibilityTests.class)
         .web(WebApplicationType.NONE)
         .properties(
-            "spring.cloud.gcp.secretmanager.project-id=" + PROJECT_NAME,
+            // "spring.cloud.gcp.secretmanager.project-id=" + PROJECT_NAME,
```
Comment (JoeWang1127) [inline spring-cloud-gcp-autoconfigure/src/test/java/com/google/cloud/spring/autoconfigure/secretmanager/SecretManagerCompatibilityTests.java:47]: Why not removing this line?

File: spring-cloud-gcp-autoconfigure/src/test/java/com/google/cloud/spring/autoconfigure/secretmanager/SecretManagerConfigDataLocationResolverUnitTests.java [hunk 5]
```diff
@@ -90,4 +97,27 @@ void registerBean() {
     when(context.getBinder()).thenReturn(new Binder());
     when(context.getBootstrapContext()).thenReturn(defaultBootstrapContext);
   }
+
+  @Test
+  void testSecretManagerProjectIdTakesPrecedence() {
+    when(secretManagerProperties.getProjectId()).thenReturn("secret-manager-property-id");
+    GcpProjectIdProvider projectIdProvider =
```
Comment (JoeWang1127) [inline spring-cloud-gcp-autoconfigure/src/test/java/com/google/cloud/spring/autoconfigure/secretmanager/SecretManagerConfigDataLocationResolverUnitTests.java:104]: Could you also add a line to setup gcpProperties? To make sure the secret manager property is indeed returned first.

File: spring-cloud-gcp-autoconfigure/src/test/java/com/google/cloud/spring/autoconfigure/secretmanager/SecretManagerConfigDataLocationResolverUnitTests.java [hunk 6]
```diff
@@ -90,4 +97,27 @@ void registerBean() {
...
+        SecretManagerConfigDataLocationResolver.createProjectIdProvider(context);
+    assertThat(projectIdProvider.getProjectId()).isEqualTo("secret-manager-property-id");
+  }
+
+  @Test
+  void testProjectIdUseCoreWhenBoSecretManagerProjectId() {
```
Comment (JoeWang1127) [inline spring-cloud-gcp-autoconfigure/src/test/java/com/google/cloud/spring/autoconfigure/secretmanager/SecretManagerConfigDataLocationResolverUnitTests.java:110]: Typo in test name?

File: spring-cloud-gcp-autoconfigure/src/main/java/com/google/cloud/spring/autoconfigure/secretmanager/SecretManagerConfigDataLocationResolver.java [hunk 7]
```diff
@@ -80,30 +84,41 @@ private static void registerSecretManagerBeans(ConfigDataLocationResolverContext
...
   }
 
-  private static GcpProjectIdProvider createProjectIdProvider(
-      ConfigDataLocationResolverContext context) {
-    GcpSecretManagerProperties properties = context.getBootstrapContext()
-        .get(GcpSecretManagerProperties.class);
-    return properties.getProjectId() != null
-        ? properties::getProjectId : new DefaultGcpProjectIdProvider();
+  @VisibleForTesting
+  static GcpProjectIdProvider createProjectIdProvider(ConfigDataLocationResolverContext context) {
```
Comment (JoeWang1127) [inline spring-cloud-gcp-autoconfigure/src/main/java/com/google/cloud/spring/autoconfigure/secretmanager/SecretManagerConfigDataLocationResolver.java:110]: Can we test the behavior without making it non private?

File: spring-cloud-gcp-autoconfigure/src/test/java/com/google/cloud/spring/autoconfigure/secretmanager/SecretManagerCompatibilityTests.java (hunk 4 above)
Comment (zhumin8) [reply spring-cloud-gcp-autoconfigure/src/test/java/com/google/cloud/spring/autoconfigure/secretmanager/SecretManagerCompatibilityTests.java]: good catch. removed.

File: spring-cloud-gcp-autoconfigure/src/test/java/com/google/cloud/spring/autoconfigure/secretmanager/SecretManagerConfigDataLocationResolverUnitTests.java (hunk 5 above)
Comment (zhumin8) [reply spring-cloud-gcp-autoconfigure/src/test/java/com/google/cloud/spring/autoconfigure/secretmanager/SecretManagerConfigDataLocationResolverUnitTests.java:105]: done b269abf622e4e06fe1ea6e210bfd883f5f4a9bf5

File: spring-cloud-gcp-autoconfigure/src/main/java/com/google/cloud/spring/autoconfigure/secretmanager/SecretManagerConfigDataLocationResolver.java (hunk 7 above)
Comment (zhumin8) [reply spring-cloud-gcp-autoconfigure/src/main/java/com/google/cloud/spring/autoconfigure/secretmanager/SecretManagerConfigDataLocationResolver.java:110]: I cannot think of a easy way to test it. Also think package-private is okay and still allow us the flexibility to changes in the future

**Review by JoeWang1127 — APPROVED** [review]
Thank you.
