### PR TITLE
Use special property to query by document Id in Firestore

### LINKED ISSUE #424: Firestore `findByIdAndArrayContains` / `existsByIdAndArrayContains` doesn't work
Hi!

I'd like to use GCP Firestore integration. Most things seem to work, except some specific queries:

Methods doing `findById` / `existsById` combined by AND with a contains on a list do not work.

**Sample**
```java
@Document(collectionName = "examples")
public class Example {
    @DocumentId
    private String id;
    private List<String> array;
}
```
```java
public interface ExampleRepository extends FirestoreReactiveRepository<Example> {
   
    Mono<Boolean> existsByIdAndArrayContains(String id, String someString); // does not work
    Mono<Boolean> existsByIdAndArrayContaining(String id, String someString); // does not work
    Mono<Boolean> existsByIdAndArrayIsContaining(String id, String someString); // does not work
    Mono<Boolean> existsByArrayContains(String someString); // works
    Mono<Boolean> existsById(String id); // works

    Mono<Example> findByIdAndArrayContains(String id, String someString); // does not work
    Mono<Example> findByIdAndArrayContaining(String id, String someString); // does not work
    Mono<Example> findByIdAndArrayIsContaining(String id, String someString); // does not work
    Mono<Example> findByArrayContains(String someString); // works
    Mono<Example> findById(String id); // works
```

`byId` and `ArrayContains` work alone but not together.

Did I miss something or is that a bug?

Thanks!

### PR DESCRIPTION
**Pull request by mpeddada1**
Fixes #424
As described in #504, this PR also replaces the use of the constant literal `__name__` with `FieldPath.documentId()`.

### CODE REVIEW

File: spring-cloud-gcp-data-firestore/src/main/java/com/google/cloud/spring/data/firestore/FirestoreTemplate.java [hunk 1]
```diff
@@ -62,61 +65,75 @@
...
 
 	private static final int FIRESTORE_WRITE_MAX_SIZE = 500;
 
-	private static final String NAME_FIELD = "__name__";
+	private static final String NOT_FOUND_DOCUMENT_MESSAGE = "NOT_FOUND: Document";
 
-	private static final StructuredQuery.Projection ID_PROJECTION = StructuredQuery.Projection.newBuilder()
-			.addFields(StructuredQuery.FieldReference.newBuilder().setFieldPath(NAME_FIELD).build())
-			.build();
+	private final String nameField = FieldPath.documentId().toString();
```
Comment (meltsufin) [inline spring-cloud-gcp-data-firestore/src/main/java/com/google/cloud/spring/data/firestore/FirestoreTemplate.java:73]: Why not `static`?

File: spring-cloud-gcp-data-firestore/src/main/java/com/google/cloud/spring/data/firestore/FirestoreTemplate.java [hunk 2]
```diff
@@ -62,61 +65,75 @@
...
-	private final FirestoreStub firestore;
+	private final FirestoreStub firestoreStub;
 
 	private final String parent;
 
 	private final String databasePath;
 
 	private final FirestoreMappingContext mappingContext;
 
+	private final Firestore firestore;
```
Comment (meltsufin) [inline spring-cloud-gcp-data-firestore/src/main/java/com/google/cloud/spring/data/firestore/FirestoreTemplate.java:89]: Why do we need both `Firestore` and `FirestoreStub`?

File: spring-cloud-gcp-data-firestore/src/main/java/com/google/cloud/spring/data/firestore/FirestoreTemplate.java [hunk 3]
```diff
@@ -62,61 +65,75 @@
...
 	/**
 	 * Constructor for FirestoreTemplate.
-	 * @param firestore Firestore gRPC stub
+	 *
+	 * @param firestoreStub Firestore gRPC stub
 	 * @param parent the parent resource. For example:
 	 *     projects/{project_id}/databases/{database_id}/documents
 	 * @param classMapper a {@link FirestoreClassMapper} used for conversion
 	 * @param mappingContext Mapping Context
+	 * @param firestore Firestore service
```
Comment (meltsufin) [inline spring-cloud-gcp-data-firestore/src/main/java/com/google/cloud/spring/data/firestore/FirestoreTemplate.java:105]: Note that this is a breaking change on a public API.

**Review by meltsufin — COMMENTED** [review]
You started with a complex module right off the bat!
Are there any documentation updates needed?

File: spring-cloud-gcp-data-firestore/src/main/java/com/google/cloud/spring/data/firestore/FirestoreTemplate.java (hunk 2 above)
Comment (elefeint) [reply spring-cloud-gcp-data-firestore/src/main/java/com/google/cloud/spring/data/firestore/FirestoreTemplate.java:89]: This was one of the experiments we did to determine feasibility. I think we can do without the extra client library object (`Firestore`) now.
`FirestoreStub` is used because the template implementation historically bypasses the client library and instead relies directly on gRPC layer. After our experiences with Spanner, I'd much rather rely on client library -- something to consider for the future, but far out of scope for this PR.

File: spring-cloud-gcp-data-firestore/src/main/java/com/google/cloud/spring/data/firestore/FirestoreTemplate.java [hunk 4]
```diff
@@ -443,4 +460,8 @@ private Object getIdValue(Object entity) {
 	public FirestoreClassMapper getClassMapper() {
 		return this.classMapper;
 	}
+
+	public DocumentReference getDocumentReference(String collection, String documentId) {
+		return this.firestore.collection(collection).document(documentId);
+	}
```
Comment (elefeint) [inline spring-cloud-gcp-data-firestore/src/main/java/com/google/cloud/spring/data/firestore/FirestoreTemplate.java:466]: I believe we can do without this method now. Once you remove it, the `Firestore` client library object can go away.

File: spring-cloud-gcp-data-firestore/src/main/java/com/google/cloud/spring/data/firestore/repository/query/PartTreeFirestoreQuery.java [hunk 5]
```diff
@@ -216,9 +220,19 @@ public Object execute(Object[] parameters) {
 							"Too few parameters are provided for query method: " + getQueryMethod().getName());
 				}
 				Object value = it.next();
-				filter.getFieldFilterBuilder().setField(fieldReference)
-						.setOp(getOperator(part, value))
-						.setValue(this.classMapper.toFirestoreValue(value));
+				if (fieldReference.getFieldPath().equals(FieldPath.documentId().toString())) {
+					FirestoreTemplate firestoreTemplate = (FirestoreTemplate) this.reactiveOperations;
+					DocumentReference documentReference = firestoreTemplate.getDocumentReference(persistentEntity.collectionName(), (String) value);
```
Comment (elefeint) [inline spring-cloud-gcp-data-firestore/src/main/java/com/google/cloud/spring/data/firestore/repository/query/PartTreeFirestoreQuery.java:225]: This field will be the same as the part we are working with in this loop iteration. So you can use `value` instead of `documentReference` when looking up the operation a couple of lines down.

File: spring-cloud-gcp-data-firestore/src/main/java/com/google/cloud/spring/data/firestore/repository/query/PartTreeFirestoreQuery.java [hunk 6]
```diff
@@ -216,9 +220,19 @@ public Object execute(Object[] parameters) {
...
+					filter.getFieldFilterBuilder().setField(fieldReference)
+							.setOp(getOperator(part, documentReference))
+							.setValue(Value.newBuilder().setReferenceValue(
+									firestoreTemplate.buildResourceName(persistentEntity, documentReference.getId())));
```
Comment (elefeint) [inline spring-cloud-gcp-data-firestore/src/main/java/com/google/cloud/spring/data/firestore/repository/query/PartTreeFirestoreQuery.java:229]: Here again, we know what the *value* of the `@DocumentId` field is without having to look it up from document reference. It's the `value` local variable!
Now, the local variable is an `Object`, while you need a `String`. But per our [documentation](https://github.com/GoogleCloudPlatform/spring-cloud-gcp/blob/main/docs/src/main/asciidoc/firestore.adoc#object-mapping), `@DocumentId` can only be applied to a `String` field since that's what Firestore uses for document IDs.

**Review by elefeint — CHANGES_REQUESTED** [review]
It's awesome that this works! The next challenge is getting `Firestore` object out of `FirestoreTemplate`, like @meltsufin noted. You should be able to do it, but it will require a change in `createBuilderWithFilter()` implementation. Once you do that work, there might be an opportunity for a small refactoring to reduce emerging duplication of code in if/else clause. I love seeing opportunities like these pop up once the large refactorings are completed.

I think the renaming of `firestore` to `firestoreStub` is a good one, since it makes the actual object's nature much clearer. However, it's a personal style preference whether to include it in the same PR as functionality changes -- it's up to you whether you want to keep it in this PR or remove it to make the current PR even smaller. Some people like to clean up small things like these as they go, and some prefer tight, targeted pull requests that only achieve the task at hand.

File: spring-cloud-gcp-data-firestore/src/main/java/com/google/cloud/spring/data/firestore/repository/query/PartTreeFirestoreQuery.java (hunk 6 above)
Comment (mpeddada1) [reply spring-cloud-gcp-data-firestore/src/main/java/com/google/cloud/spring/data/firestore/repository/query/PartTreeFirestoreQuery.java]: That is a great point! I cleaned this up a bit to use `value` directly.

File: spring-cloud-gcp-data-firestore/src/main/java/com/google/cloud/spring/data/firestore/FirestoreTemplate.java (hunk 2 above)
Comment (mpeddada1) [reply spring-cloud-gcp-data-firestore/src/main/java/com/google/cloud/spring/data/firestore/FirestoreTemplate.java]: Thanks for catching this. Sorry, I had left some experimental code in. After applying the changes @elefeint described [here](https://github.com/GoogleCloudPlatform/spring-cloud-gcp/pull/506#pullrequestreview-687777943), we no longer need to use the `Firestore` object.

**Comment by mpeddada1** [comment]
> I think the renaming of `firestore` to `firestoreStub` is a good one, since it makes the actual object's nature much clearer.
Agreed! I kept this change in this PR since it is a minor refactoring. However, as you mentioned in your comment, if the refactoring draws the reader's attention away from the purpose of the PR then having a follow-up PR is definitely a great idea.

File: spring-cloud-gcp-data-firestore/src/main/java/com/google/cloud/spring/data/firestore/FirestoreTemplate.java (hunk 4 above)
Comment (mpeddada1) [reply spring-cloud-gcp-data-firestore/src/main/java/com/google/cloud/spring/data/firestore/FirestoreTemplate.java]: Done, thank you

File: spring-cloud-gcp-data-firestore/src/main/java/com/google/cloud/spring/data/firestore/FirestoreTemplate.java (hunk 1 above)
Comment (mpeddada1) [reply spring-cloud-gcp-data-firestore/src/main/java/com/google/cloud/spring/data/firestore/FirestoreTemplate.java]: Ah `static` makes sense. Also reverted some of the unnecessary changes I made to this file.

**Comment by mpeddada1** [comment]
> Are there any documentation updates needed?

That's a good question. We may want to update the CHANGELOG for the next release?

File: spring-cloud-gcp-data-firestore/src/main/java/com/google/cloud/spring/data/firestore/FirestoreTemplate.java [hunk 7]
```diff
@@ -427,7 +434,7 @@ private void doIfTransaction(Context ctx, Consumer<ReactiveFirestoreResourceHold
 		return buildResourceName(persistentEntity, idVal.toString());
 	}
 
-	private String buildResourceName(FirestorePersistentEntity<?> persistentEntity, String s) {
+	public String buildResourceName(FirestorePersistentEntity<?> persistentEntity, String s) {
```
Comment (meltsufin) [inline spring-cloud-gcp-data-firestore/src/main/java/com/google/cloud/spring/data/firestore/FirestoreTemplate.java:437]: If we make this public, it should have a javadoc.

**Review by meltsufin — APPROVED** [review]
Just one comment on the public method javadoc.
Adding this to changelog should be sufficient I guess.

File: spring-cloud-gcp-data-firestore/src/main/java/com/google/cloud/spring/data/firestore/mapping/FirestorePersistentPropertyImpl.java [hunk 8]
```diff
@@ -61,6 +61,9 @@ public boolean isIdProperty() {
 	}
 
 	public String getFieldName() {
+		if (isIdProperty()) {
+			return FieldPath.documentId().toString();
```
Comment (elefeint) [inline spring-cloud-gcp-data-firestore/src/main/java/com/google/cloud/spring/data/firestore/mapping/FirestorePersistentPropertyImpl.java:65]: I'd rather make `NAME_FIELD` constant public and reuse it here (yep, it will need its own Javadoc then). No reason do do this dynamically for every field.

File: spring-cloud-gcp-data-firestore/src/main/java/com/google/cloud/spring/data/firestore/repository/query/PartTreeFirestoreQuery.java [hunk 9]
```diff
@@ -216,9 +219,18 @@ public Object execute(Object[] parameters) {
 							"Too few parameters are provided for query method: " + getQueryMethod().getName());
 				}
 				Object value = it.next();
-				filter.getFieldFilterBuilder().setField(fieldReference)
-						.setOp(getOperator(part, value))
-						.setValue(this.classMapper.toFirestoreValue(value));
+				StructuredQuery.FieldFilter.Builder queryFilterBuilder = filter.getFieldFilterBuilder()
+						.setField(fieldReference).setOp(getOperator(part, value));
+				if (fieldReference.getFieldPath().equals(FieldPath.documentId().toString())) {
```
Comment (elefeint) [inline spring-cloud-gcp-data-firestore/src/main/java/com/google/cloud/spring/data/firestore/repository/query/PartTreeFirestoreQuery.java:224]: Same here, reuse `NAME_FIELD`

File: spring-cloud-gcp-data-firestore/src/main/java/com/google/cloud/spring/data/firestore/repository/query/PartTreeFirestoreQuery.java [hunk 10]
```diff
@@ -216,9 +219,18 @@ public Object execute(Object[] parameters) {
...
+					FirestoreTemplate firestoreTemplate = (FirestoreTemplate) this.reactiveOperations;
```
Comment (elefeint) [inline spring-cloud-gcp-data-firestore/src/main/java/com/google/cloud/spring/data/firestore/repository/query/PartTreeFirestoreQuery.java:225]: In real life, `reactiveOperations` will almost always be of type `FirestoreTemplate`. However, that's not guaranteed!
Also, for testing, if we want to mock `reactiveOperations`, this line will fail. 

I would instead suggest adding `buildResourceName()` as a valid interface method on `FirestoreReactiveOperations` (btw, then the javadoc will go on the interface method, and not on implementation). This will make it a proper part of the API, which we can then mock for testing or be required to implement for an alternate implementation.

File: spring-cloud-gcp-data-firestore/src/main/java/com/google/cloud/spring/data/firestore/repository/query/PartTreeFirestoreQuery.java [hunk 11]
```diff
@@ -216,9 +219,18 @@ public Object execute(Object[] parameters) {
...
+					queryFilterBuilder
+							.setValue(Value.newBuilder().setReferenceValue(
+									firestoreTemplate.buildResourceName(persistentEntity, (String) value)));
```
Comment (elefeint) [inline spring-cloud-gcp-data-firestore/src/main/java/com/google/cloud/spring/data/firestore/repository/query/PartTreeFirestoreQuery.java:228]: For future developers, I'd add a comment for why we can assume value is always a `String`.

File: spring-cloud-gcp-data-firestore/src/test/java/com/google/cloud/spring/data/firestore/entities/UserRepository.java [hunk 12]
```diff
@@ -56,6 +58,8 @@
 
 	Flux<User> findByAgeAndPetsContains(Integer age, List<String> pets);
 
+	Flux<User> findByNameAndPetsContains(String name, List<String> pets);
```
Comment (elefeint) [inline spring-cloud-gcp-data-firestore/src/test/java/com/google/cloud/spring/data/firestore/entities/UserRepository.java:61]: Great addition to testing, since that's what the original issue cited!

**Review by elefeint — CHANGES_REQUESTED** [review]
This is looking great. Still, we can future-proof and help ourselves with future testing a bit more.

File: spring-cloud-gcp-data-firestore/src/main/java/com/google/cloud/spring/data/firestore/FirestoreTemplate.java (hunk 7 above)
Comment (mpeddada1) [reply spring-cloud-gcp-data-firestore/src/main/java/com/google/cloud/spring/data/firestore/FirestoreTemplate.java]: Good point, done.

File: spring-cloud-gcp-data-firestore/src/main/java/com/google/cloud/spring/data/firestore/repository/query/PartTreeFirestoreQuery.java (hunk 10 above)
Comment (mpeddada1) [reply spring-cloud-gcp-data-firestore/src/main/java/com/google/cloud/spring/data/firestore/repository/query/PartTreeFirestoreQuery.java]: > Also, for testing, if we want to mock reactiveOperations, this line will fail.

Ah I did not think of this, thank you!

File: spring-cloud-gcp-data-firestore/src/main/java/com/google/cloud/spring/data/firestore/repository/query/PartTreeFirestoreQuery.java (hunk 11 above)
Comment (mpeddada1) [reply spring-cloud-gcp-data-firestore/src/main/java/com/google/cloud/spring/data/firestore/repository/query/PartTreeFirestoreQuery.java]: Done.

File: spring-cloud-gcp-data-firestore/src/test/java/com/google/cloud/spring/data/firestore/repository/query/FirestoreRepositoryTests.java [hunk 13]
```diff
@@ -70,7 +71,7 @@ public void testSortQuery() {
 				Order.newBuilder()
 						.setDirection(Direction.ASCENDING)
 						.setField(
-								FieldReference.newBuilder().setFieldPath("name"))
+								FieldReference.newBuilder().setFieldPath(FieldPath.documentId().toString()))
```
Comment (elefeint) [inline spring-cloud-gcp-data-firestore/src/test/java/com/google/cloud/spring/data/firestore/repository/query/FirestoreRepositoryTests.java:74]: This is an interesting change. The former line used "name"; the current uses "__name__", so at first glance, it looks like a behavior change. But! Notice, this is a unit test (well, it's a unit test for a fairly large "unit" extending from "spring data parses repository method name" to "firestore template execute called"). So while this test "used to work", this same test would fail in an integration test setup. 

So this got me to wonder... Did our sort by ID property works at all? And when I wonder whether something works, I write an integration test :

_FirestoreRepositoryIntegrationTests_
```
	@Test
	public void testOrderByDocumentId() {
		User alice = new User("Alice", 99);
		User bob = new User("Bob", 99);
		User zelda = new User("Zelda", 99);
		this.userRepository.save(alice)
				.then(this.userRepository.save(bob))
				.then(this.userRepository.save(zelda))
				.block();

		StepVerifier.create(
				this.userRepository.findByAge(99, Sort.by(Order.desc("name"))).map(User::getName)
		).expectNext("Zelda", "Bob", "Alice")
				.verifyComplete();
	}
```

So, get this: the test fails on `main` branch, and passes on your pull request. Congratulations on fixing a bug we never knew we had!

**Review by elefeint — APPROVED** [review]
Excellent! By the way, you fixed *two* bugs, one of which we never knew about.
