### PR TITLE
fix: add supported type to Spanner read to query option conversion

### LINKED ISSUE #1306: Unable to include tag option to SpTemplate.read(..., SpannerReadOptions)
**Describe the bug**
Even though options.tag is a ReadQueryUpdateTransactionOption and valid to pass to addQueryOption() and addReadOption() in their respective Spanner{Read,Query}Options definitions, it fails when you pass a valid read option to SpannerTemplate.read.

```
java.lang.IllegalArgumentException: Can't convert com.google.cloud.spring.data.spanner.core.SpannerReadOptions@7c3d17a6 to SpannerQueryOptions 

	at com.google.cloud.spring.data.spanner.core.SpannerReadOptions.toQueryOptions(SpannerReadOptions.java:102)
	at com.google.cloud.spring.data.spanner.core.SpannerTemplate.toQueryOption(SpannerTemplate.java:240)
	at com.google.cloud.spring.data.spanner.core.SpannerTemplate.read(SpannerTemplate.java:208)
	at com.google.cloud.spring.data.spanner.core.SpannerTemplate.read(SpannerTemplate.java:188)
```

I'm pretty sure this fails because the tag isn't a member of Options.ReadAndQueryOption, which is checked in checked [in .toQueryOptions](https://github.com/GoogleCloudPlatform/spring-cloud-gcp/blob/main/spring-cloud-gcp-data-spanner/src/main/java/com/google/cloud/spring/data/spanner/core/SpannerReadOptions.java#L98) even though it implements both Read and Query options.

While I'm here complaining about tags, it'd be great to get transaction options to expose tag support as well.

### PR DESCRIPTION
**Pull request by emmileaf**
Fixes #1306 which points out a missed condition: when converting Spanner `ReadOption` to `QueryOption`, [`ReadQueryUpdateTransactionOption`](https://github.com/googleapis/java-spanner/blob/d59e2db88a365a6c119040983459eb3f1b98dfe5/google-cloud-spanner/src/main/java/com/google/cloud/spanner/Options.java#L51) should also result in a valid conversion.

### CODE REVIEW

**Review by elefeint — APPROVED** [review]
If we need to add another option over time, a map or an enum mapping might make sense.

File: spring-cloud-gcp-data-spanner/src/test/java/com/google/cloud/spring/data/spanner/core/SpannerReadOptionsTests.java [hunk 1]
```diff
@@ -46,6 +48,26 @@ void addReadOptionTest() {
...
+    SpannerQueryOptions spannerQueryOptions = spannerReadOptions.toQueryOptions();
+    assertThat(spannerQueryOptions.getOptions()).hasSize(2);
+  }
+
+  @Test
+  void convertReadToQueryOptionTest_throwIfNotSupported() {
+    SpannerReadOptions spannerReadOptions = new SpannerReadOptions();
+    ReadOption r1 = mock(ReadOption.class);
+    spannerReadOptions.addReadOption(r1);
+    assertThatThrownBy(() -> spannerReadOptions.toQueryOptions())
```
Comment (JoeWang1127) [inline spring-cloud-gcp-data-spanner/src/test/java/com/google/cloud/spring/data/spanner/core/SpannerReadOptionsTests.java:66]: nit: you can replace lambda with method reference.

File: spring-cloud-gcp-data-spanner/src/test/java/com/google/cloud/spring/data/spanner/core/SpannerTemplateTests.java [hunk 2]
```diff
@@ -450,6 +451,19 @@ void findKeySetTestEagerOptions() {
...
+  @Test
+  void findKeySetTestEagerConvertedOptions() {
+    SpannerTemplate spyTemplate = spy(this.spannerTemplate);
+    KeySet keys = KeySet.newBuilder().addKey(Key.of("key1")).addKey(Key.of("key2")).build();
+    SpannerReadOptions options =
+            new SpannerReadOptions()
+                    .addReadOption(mock(Options.ReadAndQueryOption.class))
+                    .addReadOption(mock(Options.ReadQueryUpdateTransactionOption.class));
+    spyTemplate.read(ParentEntity.class, keys, options);
+    verify(spyTemplate, times(1)).read(eq(ParentEntity.class), same(keys), eq(options));
```
Comment (zhumin8) [inline spring-cloud-gcp-data-spanner/src/test/java/com/google/cloud/spring/data/spanner/core/SpannerTemplateTests.java:463]: nit: `times(1)` can be omitted, `verify(mock)` is alias to verify(mock, times(1)) 
```suggestion
    verify(spyTemplate).read(eq(ParentEntity.class), same(keys), eq(options));
```

**Review by zhumin8 — APPROVED** [review]
LGTM!

**Review by JoeWang1127 — APPROVED** [review]
LGTM
