### PR TITLE
Close Spanner health check ResultSet to prevent session leak

### LINKED ISSUE #891: Connectivity issues with Spanner on 2.0.6 and above
**Describe the bug**
Trying to do a "SELECT 1" on a Spanner database fails.  Attached a stack trace from the example. I could reproduce this only with versions 2.0.6 and 2.0.7. Earlier versions are working fine.
```
java.util.concurrent.TimeoutException: null
	at java.base/java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1960) ~[na:na]
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2095) ~[na:na]
	at com.rewe.spannerproblem.config.SpannerHealthCheck.doHealthCheck(SpannerHealthCheck.java:46) ~[classes/:na]
	at org.springframework.boot.actuate.health.AbstractHealthIndicator.health(AbstractHealthIndicator.java:82) ~[spring-boot-actuator-2.6.1.jar:2.6.1]
	at org.springframework.boot.actuate.health.HealthIndicator.getHealth(HealthIndicator.java:37) ~[spring-boot-actuator-2.6.1.jar:2.6.1]
	at org.springframework.boot.actuate.health.HealthEndpointWebExtension.getHealth(HealthEndpointWebExtension.java:87) ~[spring-boot-actuator-2.6.1.jar:2.6.1]
	at org.springframework.boot.actuate.health.HealthEndpointWebExtension.getHealth(HealthEndpointWebExtension.java:45) ~[spring-boot-actuator-2.6.1.jar:2.6.1]
	at org.springframework.boot.actuate.health.HealthEndpointSupport.getContribution(HealthEndpointSupport.java:130) ~[spring-boot-actuator-2.6.1.jar:2.6.1]
	at org.springframework.boot.actuate.health.HealthEndpointSupport.getAggregateContribution(HealthEndpointSupport.java:141) ~[spring-boot-actuator-2.6.1.jar:2.6.1]
	at org.springframework.boot.actuate.health.HealthEndpointSupport.getContribution(HealthEndpointSupport.java:126) ~[spring-boot-actuator-2.6.1.jar:2.6.1]
	at org.springframework.boot.actuate.health.HealthEndpointSupport.getHealth(HealthEndpointSupport.java:95) ~[spring-boot-actuator-2.6.1.jar:2.6.1]
	at org.springframework.boot.actuate.health.HealthEndpointSupport.getHealth(HealthEndpointSupport.java:66) ~[spring-boot-actuator-2.6.1.jar:2.6.1]
	at org.springframework.boot.actuate.health.HealthEndpointWebExtension.health(HealthEndpointWebExtension.java:73) ~[spring-boot-actuator-2.6.1.jar:2.6.1]
	at org.springframework.boot.actuate.health.HealthEndpointWebExtension.health(HealthEndpointWebExtension.java:62) ~[spring-boot-actuator-2.6.1.jar:2.6.1]
	at jdk.internal.reflect.GeneratedMethodAccessor54.invoke(Unknown Source) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:568) ~[na:na]
	at org.springframework.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:282) ~[spring-core-5.3.13.jar:5.3.13]
	at org.springframework.boot.actuate.endpoint.invoke.reflect.ReflectiveOperationInvoker.invoke
```

Let me know if you have any further doubts or require more information.

**Sample**

https://github.com/Daniel-OG/Spanner-problem

### PR DESCRIPTION
**Pull request by elefeint**
Verified that the session pool stays stable after the fix using one of the Spanner samples, plus actuator dependency.

Fixes #891.

### CODE REVIEW

File: spring-cloud-gcp-autoconfigure/src/main/java/com/google/cloud/spring/autoconfigure/spanner/health/SpannerHealthIndicator.java [hunk 1]
```diff
@@ -55,6 +55,8 @@ protected void doHealthCheck(Builder builder) throws Exception {
     ResultSet resultSet = spannerTemplate.executeQuery(validationStatement, null);
     // Touch the record
     resultSet.next();
+    resultSet.close();
```
Comment (meltsufin) [inline spring-cloud-gcp-autoconfigure/src/main/java/com/google/cloud/spring/autoconfigure/spanner/health/SpannerHealthIndicator.java:58]: Can you do try-with-resource here?

**Review by meltsufin — CHANGES_REQUESTED** [review]

File: spring-cloud-gcp-autoconfigure/src/main/java/com/google/cloud/spring/autoconfigure/spanner/health/SpannerHealthIndicator.java (hunk 1 above)
Comment (elefeint) [reply spring-cloud-gcp-autoconfigure/src/main/java/com/google/cloud/spring/autoconfigure/spanner/health/SpannerHealthIndicator.java:58]: sure

**Review by meltsufin — APPROVED** [review]
