### PR TITLE
Find the lost transaction manager

### LINKED ISSUE #1297: Firestore: No qualifying bean of type 'org.springframework.transaction.TransactionManager' available
**Describe the bug**
`org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'org.springframework.transaction.TransactionManager' available`

As soon as I upgraded some dependencies the @Transactional annotation stopped working.
Original working versions are:
```xml
<groupId>org.springframework.boot</groupId>
<artifactId>spring-boot-starter-parent</artifactId>
<version>2.5.5</version>
```
+
```xml
<groupId>com.google.cloud</groupId>
<artifactId>spring-cloud-gcp-dependencies</artifactId>
<version>2.0.4</version>
```

Tried with some different versions combinations. Latest with:
```xml
<groupId>org.springframework.boot</groupId>
<artifactId>spring-boot-starter-parent</artifactId>
<version>2.6.12</version>
```
+
```xml
<groupId>com.google.cloud</groupId>
<artifactId>spring-cloud-gcp-dependencies</artifactId>
<version>3.3.0</version>
```
Since https://github.com/GoogleCloudPlatform/spring-cloud-gcp mentions GCP3.x should be compatible with Spring Boot 2.6.x

**Sample**
Minimum sample can be found here: https://github.com/VitorBittencourt/transaction-error.git
To test, just start the app (I'm using firestore emulator, but same error was first seen in the real thing) and send a
POST request to localhost:8080/foo/save/123

### PR DESCRIPTION
**Pull request by elefeint**
As part of https://github.com/GoogleCloudPlatform/spring-cloud-gcp/pull/620, the transaction manager autoconfiguration was removed from the main Firestore autoconfig but was not added to Spring's metadata, so it's not automatically loaded.

This PR:
1) Brings back the transaction manager in `spring.factories` (we'll have to re-add for the New Way in Boot 3.0).
2) Adds a service between controller and repository, but for only one method.
3) Strengthens the test by verifying that HTTP call does not fail, but only for one method.

I'll either send a follow-up to do 2) and 3) for the remaining functionality or leave them as an exercise for the reader :)

Fixes #1297.

### CODE REVIEW

File: spring-cloud-gcp-samples/spring-cloud-gcp-data-firestore-sample/src/main/java/com/example/UserService.java [hunk 1]
```diff
@@ -0,0 +1,40 @@
...
+package com.example;
+
+import org.springframework.stereotype.Service;
+import org.springframework.transaction.annotation.Transactional;
+import reactor.core.publisher.Mono;
+
+@Service
+public class UserService {
+
+  private UserRepository userRepository;
```
Comment (JoeWang1127) [inline spring-cloud-gcp-samples/spring-cloud-gcp-data-firestore-sample/src/main/java/com/example/UserService.java:26]: nit: `userRepository` should be `final`.

**Review by JoeWang1127 — APPROVED** [review]
LGTM
