### PR TITLE
fix: make UserAgentHeaderProvider Serializable

### LINKED ISSUE #3665: Unable to serialize `RestorableState<WriteChannel>` that is created via autoconfigured `Storage` bean
**Describe the bug**
Bug:
When attempting to persist our `RestorableState<WriteChannel>` for later use, we receive an exception:
`java.io.NotSerializableException: com.google.cloud.spring.core.UserAgentHeaderProvider`. This is because
`UserAgentHeaderProvider` does not implement the `java.io.Serializable` interface.

Context:
- `GcpStorageAutoConfiguration` creates a `Storage` bean
  - To instantiate the `Storage` bean, a `StorageOptions` is built
  - A `UserAgentHeaderProvider` is set on this `StorageOptions`
- A `WriteChannel` can be created using this `Storage` bean via `Storage.writer()`
- We can create a `RestorableState<WriteChannel>` via `WriteChannel.capture()`
  - In this particular case, we have a `BlobWriteChannelV2State`
- `BlobWriteChannelV2State` implements `java.io.Serializable`
  - `BlobWriteChannelV2State` contains a copy of the original `StorageOptions` created by the autoconfiguration
  - This `StorageOptions` contains a `UserAgentHeaderProvider`

**Sample**
1. Autowire the autoconfigured `Storage` bean
2. Create a `WriteChannel` via `Storage.writer()`
3. Create a `RestorableState<WriteChannel>` via `WriteChannel.capture()`
4. Attempt to serialize the `RestorableState<WriteChannel>`
5. Observe the exception

### PR DESCRIPTION
**Pull request by zhumin8**
This PR is created based on #3676.

[StorageOptions](https://github.com/googleapis/java-storage/blob/main/google-cloud-storage/src/main/java/com/google/cloud/storage/StorageOptions.java#L41) is Serializable. It extends [ServiceOptions](https://github.com/googleapis/sdk-platform-java/blob/0be1e9670079bcf6a9246d0284e59001c24242ea/java-core/google-cloud-core/src/main/java/com/google/cloud/ServiceOptions.java#L83) in google-cloud-core. So this UserAgentHeaderProvider that is set to StorageOptions [here](https://github.com/GoogleCloudPlatform/spring-cloud-gcp/blob/a2efc4af6b39d82df0f636f2dd8b03fa91bff0a4/spring-cloud-gcp-autoconfigure/src/main/java/com/google/cloud/spring/autoconfigure/storage/GcpStorageAutoConfiguration.java#L86) in autoconfig needs to be Serializable.

serialVersionUID is calculated with
```
serialver -classpath path/to/google-cloud-core-2.58.0.jar:/path/to/gax-2.68.0.jar com.google.cloud.spring.core.UserAgentHeaderProvider
```
b/428237849
Fixes #3665
Thank you @ajbenjam for contributing!

### CODE REVIEW

**Comment by jinseopkim0** [comment]
Are the failing tests unrelated to the PR?

**Comment by zhumin8** [comment]
Native test failed with 
```
  JUnit Jupiter:GoogleStorageIntegrationTests:testRestorableStateSerialization()
    MethodSource [className = 'com.google.cloud.spring.storage.it.GoogleStorageIntegrationTests', methodName = 'testRestorableStateSerialization', methodParameterTypes = '']
    => com.oracle.svm.core.jdk.UnsupportedFeatureError: SerializationConstructorAccessor class not found for declaringClass: com.google.cloud.storage.BlobWriteChannelV2$BlobWriteChannelV2State (targetConstructorClass: java.lang.Object). Usually adding com.google.cloud.storage.BlobWriteChannelV2$BlobWriteChannelV2State to serialization-config.json fixes the problem.
```

File: spring-cloud-gcp-storage/src/test/java/com/google/cloud/spring/storage/it/GoogleStorageIntegrationTests.java [hunk 1]
```diff
@@ -125,6 +129,24 @@ void createWithContent() throws IOException {
     }
   }
 
+  @Test
+  @DisabledInAotMode
```
Comment (zhumin8) [inline spring-cloud-gcp-storage/src/test/java/com/google/cloud/spring/storage/it/GoogleStorageIntegrationTests.java:133]: Regarding test failure (see [comment](https://github.com/GoogleCloudPlatform/spring-cloud-gcp/pull/3935#issuecomment-3059942697)). 
Alternatively, we can add hint as
```
 hints.serialization().registerType(
        TypeReference.of("com.google.cloud.storage.BlobWriteChannelV2$BlobWriteChannelV2State"));
```
to let this test pass in GraalVM.



This test verifies that the RestorableState object, captured from the WriteChannel, can be passed to an ObjectOutputStream without throwing a NotSerializableException. This effectively checks that the state object is serializable.
While this is a valid integration test to confirm the fix, it's better to focus on public surface exposed by this repo itself for native image compatibility tests. Thus is simpler and appropriate to disable this test for AOT mode.

**Review by jinseopkim0 — APPROVED** [review]
